name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  email_validator: ^1.0.5
  rflutter_alert: ^1.0.3
  google_sign_in: ^4.5.1
  modal_progress_hud: ^0.1.3
  mask_text_input_formatter: ^1.0.7
  flutter_facebook_login: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
